services: 
  - name: docker:dind
    entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - package

docker-build-prod:
  stage: build
  image: maven:3.8.4-openjdk-17
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
  - mvn -f adminserver/pom.xml clean package
  - mvn -f centralized-configuration-client/pom.xml clean package
  - mvn -f centralized-configuration-server/pom.xml clean package
  - mvn -f eureka-server/pom.xml clean package
  - mvn -f products/pom.xml clean package

docker-build-dev:
  stage: build
  image: maven:3.8.4-openjdk-17
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
  - mvn -f adminserver/pom.xml clean package
  - mvn -f centralized-configuration-client/pom.xml clean package
  - mvn -f centralized-configuration-server/pom.xml clean package
  - mvn -f eureka-server/pom.xml clean package
  - mvn -f products/pom.xml clean package
  
docker-package-prod:
  stage: package
  image: docker/compose
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
  - mvn -f adminserver/pom.xml clean package
  - mvn -f centralized-configuration-client/pom.xml clean package
  - mvn -f centralized-configuration-server/pom.xml clean package
  - mvn -f eureka-server/pom.xml clean package
  - mvn -f products/pom.xml clean package
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker-compose build
  - docker-compose push --ignore-push-failures

docker-package-dev:
  stage: package
  image: docker/compose
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker-compose build
  - docker-compose push --ignore-push-failures
