image: docker/compose
services: 
  - name: docker:dind
    entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - package


docker-build-prod:
  stage: package
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker-compose build
  - docker tag etudiant-startuppeur:latest registry.gitlab.com/c3156/microservice/anas-el-abed/prod
  - docker push registry.gitlab.com/c3156/microservice/anas-el-abed/prod

docker-build-dev:
  stage: package
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker-compose build
  - docker tag etudiant-startuppeur:latest registry.gitlab.com/c3156/microservice/anas-el-abed/dev
  - docker push registry.gitlab.com/c3156/microservice/anas-el-abed/dev
