image: docker/compose
services: 
  - name: docker:dind
    entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - package

docker-build-prod:
  stage: package
  image: maven:3.8.4-openjdk-17
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
  - mvn -f adminserver/pom.xml clean package
  - mvn -f centralized-configuration-client/pom.xml clean package
  - mvn -f centralized-configuration-server/pom.xml clean package
  - mvn -f eureka-server/pom.xml clean package
  - mvn -f products/pom.xml clean package
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker-compose build
  - docker-compose push --ignore-push-failures

docker-build-dev:
  stage: package
  image: maven:3.8.4-openjdk-17
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  before_script:
  - mvn -f adminserver/pom.xml clean package
  - mvn -f centralized-configuration-client/pom.xml clean package
  - mvn -f centralized-configuration-server/pom.xml clean package
  - mvn -f eureka-server/pom.xml clean package
  - mvn -f products/pom.xml clean package
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker-compose build
  - docker tag adminserver registry.gitlab.com/c3156/microservice/anas-el-abed/admin-server:dev
  - docker tag configserver registry.gitlab.com/c3156/microservice/anas-el-abed/config-server:dev
  - docker tag eurekaserver registry.gitlab.com/c3156/microservice/anas-el-abed/eureka-server:dev
  - docker tag clientserver registry.gitlab.com/c3156/microservice/anas-el-abed/client-server:dev
  - docker tag product registry.gitlab.com/c3156/microservice/anas-el-abed/product-server:dev
  - docker push registry.gitlab.com/c3156/microservice/anas-el-abed/admin-server:dev
  - docker push registry.gitlab.com/c3156/microservice/anas-el-abed/config-server:dev
  - docker push registry.gitlab.com/c3156/microservice/anas-el-abed/eureka-server:dev
  - docker push registry.gitlab.com/c3156/microservice/anas-el-abed/client-server:dev
  - docker push registry.gitlab.com/c3156/microservice/anas-el-abed/product-server:dev
