management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 9128
spring:
  boot:
    admin:
      client:
        url: http://localhost:9919
  application:
    name: eureka-server
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:9128/eureka/
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: SpringBootKeycloak
  resource: login-app
  public-client: true
  security-constraints:
    - authRoles: [user]
      securityCollections:
        - name: eureka
          patterns: ['/*']
    
  principal-attribute: preferred_username